// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.taoeaten.et.protobuf;

public final class CommandProtobuf {
  private CommandProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmdNo = 1;
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    boolean hasCmdNo();
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    int getCmdNo();

    // required string userName = 2;
    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // optional int32 roomNo = 3;
    /**
     * <code>optional int32 roomNo = 3;</code>
     */
    boolean hasRoomNo();
    /**
     * <code>optional int32 roomNo = 3;</code>
     */
    int getRoomNo();

    // optional int32 userReady = 4;
    /**
     * <code>optional int32 userReady = 4;</code>
     */
    boolean hasUserReady();
    /**
     * <code>optional int32 userReady = 4;</code>
     */
    int getUserReady();

    // repeated .com.taoeaten.et.protobuf.Room rooms = 5;
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room> 
        getRoomsList();
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    com.taoeaten.et.protobuf.CommandProtobuf.Room getRooms(int index);
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    int getRoomsCount();
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    java.util.List<? extends com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder> 
        getRoomsOrBuilderList();
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder getRoomsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.taoeaten.et.protobuf.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmdNo_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roomNo_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userReady_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                rooms_ = new java.util.ArrayList<com.taoeaten.et.protobuf.CommandProtobuf.Room>();
                mutable_bitField0_ |= 0x00000010;
              }
              rooms_.add(input.readMessage(com.taoeaten.et.protobuf.CommandProtobuf.Room.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoeaten.et.protobuf.CommandProtobuf.Command.class, com.taoeaten.et.protobuf.CommandProtobuf.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmdNo = 1;
    public static final int CMDNO_FIELD_NUMBER = 1;
    private int cmdNo_;
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    public boolean hasCmdNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    public int getCmdNo() {
      return cmdNo_;
    }

    // required string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 roomNo = 3;
    public static final int ROOMNO_FIELD_NUMBER = 3;
    private int roomNo_;
    /**
     * <code>optional int32 roomNo = 3;</code>
     */
    public boolean hasRoomNo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 roomNo = 3;</code>
     */
    public int getRoomNo() {
      return roomNo_;
    }

    // optional int32 userReady = 4;
    public static final int USERREADY_FIELD_NUMBER = 4;
    private int userReady_;
    /**
     * <code>optional int32 userReady = 4;</code>
     */
    public boolean hasUserReady() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 userReady = 4;</code>
     */
    public int getUserReady() {
      return userReady_;
    }

    // repeated .com.taoeaten.et.protobuf.Room rooms = 5;
    public static final int ROOMS_FIELD_NUMBER = 5;
    private java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room> rooms_;
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    public java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room> getRoomsList() {
      return rooms_;
    }
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    public java.util.List<? extends com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder> 
        getRoomsOrBuilderList() {
      return rooms_;
    }
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    public int getRoomsCount() {
      return rooms_.size();
    }
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    public com.taoeaten.et.protobuf.CommandProtobuf.Room getRooms(int index) {
      return rooms_.get(index);
    }
    /**
     * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
     */
    public com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder getRoomsOrBuilder(
        int index) {
      return rooms_.get(index);
    }

    private void initFields() {
      cmdNo_ = 0;
      userName_ = "";
      roomNo_ = 0;
      userReady_ = 0;
      rooms_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRoomsCount(); i++) {
        if (!getRooms(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmdNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, roomNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, userReady_);
      }
      for (int i = 0; i < rooms_.size(); i++) {
        output.writeMessage(5, rooms_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roomNo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userReady_);
      }
      for (int i = 0; i < rooms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rooms_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taoeaten.et.protobuf.CommandProtobuf.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoeaten.et.protobuf.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taoeaten.et.protobuf.CommandProtobuf.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoeaten.et.protobuf.CommandProtobuf.Command.class, com.taoeaten.et.protobuf.CommandProtobuf.Command.Builder.class);
      }

      // Construct using com.taoeaten.et.protobuf.CommandProtobuf.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoomsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmdNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roomNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        userReady_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Command_descriptor;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Command getDefaultInstanceForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.Command.getDefaultInstance();
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Command build() {
        com.taoeaten.et.protobuf.CommandProtobuf.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Command buildPartial() {
        com.taoeaten.et.protobuf.CommandProtobuf.Command result = new com.taoeaten.et.protobuf.CommandProtobuf.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdNo_ = cmdNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roomNo_ = roomNo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userReady_ = userReady_;
        if (roomsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            rooms_ = java.util.Collections.unmodifiableList(rooms_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.rooms_ = rooms_;
        } else {
          result.rooms_ = roomsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoeaten.et.protobuf.CommandProtobuf.Command) {
          return mergeFrom((com.taoeaten.et.protobuf.CommandProtobuf.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoeaten.et.protobuf.CommandProtobuf.Command other) {
        if (other == com.taoeaten.et.protobuf.CommandProtobuf.Command.getDefaultInstance()) return this;
        if (other.hasCmdNo()) {
          setCmdNo(other.getCmdNo());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasRoomNo()) {
          setRoomNo(other.getRoomNo());
        }
        if (other.hasUserReady()) {
          setUserReady(other.getUserReady());
        }
        if (roomsBuilder_ == null) {
          if (!other.rooms_.isEmpty()) {
            if (rooms_.isEmpty()) {
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRoomsIsMutable();
              rooms_.addAll(other.rooms_);
            }
            onChanged();
          }
        } else {
          if (!other.rooms_.isEmpty()) {
            if (roomsBuilder_.isEmpty()) {
              roomsBuilder_.dispose();
              roomsBuilder_ = null;
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000010);
              roomsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoomsFieldBuilder() : null;
            } else {
              roomsBuilder_.addAllMessages(other.rooms_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdNo()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        for (int i = 0; i < getRoomsCount(); i++) {
          if (!getRooms(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoeaten.et.protobuf.CommandProtobuf.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoeaten.et.protobuf.CommandProtobuf.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmdNo = 1;
      private int cmdNo_ ;
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public boolean hasCmdNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public int getCmdNo() {
        return cmdNo_;
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public Builder setCmdNo(int value) {
        bitField0_ |= 0x00000001;
        cmdNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public Builder clearCmdNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdNo_ = 0;
        onChanged();
        return this;
      }

      // required string userName = 2;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      // optional int32 roomNo = 3;
      private int roomNo_ ;
      /**
       * <code>optional int32 roomNo = 3;</code>
       */
      public boolean hasRoomNo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 roomNo = 3;</code>
       */
      public int getRoomNo() {
        return roomNo_;
      }
      /**
       * <code>optional int32 roomNo = 3;</code>
       */
      public Builder setRoomNo(int value) {
        bitField0_ |= 0x00000004;
        roomNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomNo = 3;</code>
       */
      public Builder clearRoomNo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roomNo_ = 0;
        onChanged();
        return this;
      }

      // optional int32 userReady = 4;
      private int userReady_ ;
      /**
       * <code>optional int32 userReady = 4;</code>
       */
      public boolean hasUserReady() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 userReady = 4;</code>
       */
      public int getUserReady() {
        return userReady_;
      }
      /**
       * <code>optional int32 userReady = 4;</code>
       */
      public Builder setUserReady(int value) {
        bitField0_ |= 0x00000008;
        userReady_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userReady = 4;</code>
       */
      public Builder clearUserReady() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userReady_ = 0;
        onChanged();
        return this;
      }

      // repeated .com.taoeaten.et.protobuf.Room rooms = 5;
      private java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room> rooms_ =
        java.util.Collections.emptyList();
      private void ensureRoomsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          rooms_ = new java.util.ArrayList<com.taoeaten.et.protobuf.CommandProtobuf.Room>(rooms_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.taoeaten.et.protobuf.CommandProtobuf.Room, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder, com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder> roomsBuilder_;

      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room> getRoomsList() {
        if (roomsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rooms_);
        } else {
          return roomsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public int getRoomsCount() {
        if (roomsBuilder_ == null) {
          return rooms_.size();
        } else {
          return roomsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public com.taoeaten.et.protobuf.CommandProtobuf.Room getRooms(int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);
        } else {
          return roomsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder setRooms(
          int index, com.taoeaten.et.protobuf.CommandProtobuf.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.set(index, value);
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder setRooms(
          int index, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.set(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder addRooms(com.taoeaten.et.protobuf.CommandProtobuf.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder addRooms(
          int index, com.taoeaten.et.protobuf.CommandProtobuf.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(index, value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder addRooms(
          com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder addRooms(
          int index, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder addAllRooms(
          java.lang.Iterable<? extends com.taoeaten.et.protobuf.CommandProtobuf.Room> values) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          super.addAll(values, rooms_);
          onChanged();
        } else {
          roomsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder clearRooms() {
        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public Builder removeRooms(int index) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.remove(index);
          onChanged();
        } else {
          roomsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder getRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder getRoomsOrBuilder(
          int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);  } else {
          return roomsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public java.util.List<? extends com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder> 
           getRoomsOrBuilderList() {
        if (roomsBuilder_ != null) {
          return roomsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rooms_);
        }
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder addRoomsBuilder() {
        return getRoomsFieldBuilder().addBuilder(
            com.taoeaten.et.protobuf.CommandProtobuf.Room.getDefaultInstance());
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder addRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().addBuilder(
            index, com.taoeaten.et.protobuf.CommandProtobuf.Room.getDefaultInstance());
      }
      /**
       * <code>repeated .com.taoeaten.et.protobuf.Room rooms = 5;</code>
       */
      public java.util.List<com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder> 
           getRoomsBuilderList() {
        return getRoomsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.taoeaten.et.protobuf.CommandProtobuf.Room, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder, com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder> 
          getRoomsFieldBuilder() {
        if (roomsBuilder_ == null) {
          roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.taoeaten.et.protobuf.CommandProtobuf.Room, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder, com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder>(
                  rooms_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          rooms_ = null;
        }
        return roomsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.taoeaten.et.protobuf.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taoeaten.et.protobuf.Command)
  }

  public interface RoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 roomId = 1;
    /**
     * <code>required int32 roomId = 1;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required int32 roomId = 1;</code>
     */
    int getRoomId();
  }
  /**
   * Protobuf type {@code com.taoeaten.et.protobuf.Room}
   */
  public static final class Room extends
      com.google.protobuf.GeneratedMessage
      implements RoomOrBuilder {
    // Use Room.newBuilder() to construct.
    private Room(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Room(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Room defaultInstance;
    public static Room getDefaultInstance() {
      return defaultInstance;
    }

    public Room getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Room(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Room_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Room_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoeaten.et.protobuf.CommandProtobuf.Room.class, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder.class);
    }

    public static com.google.protobuf.Parser<Room> PARSER =
        new com.google.protobuf.AbstractParser<Room>() {
      public Room parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Room(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Room> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 roomId = 1;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>required int32 roomId = 1;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 roomId = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    private void initFields() {
      roomId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roomId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.Room parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taoeaten.et.protobuf.CommandProtobuf.Room prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoeaten.et.protobuf.Room}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taoeaten.et.protobuf.CommandProtobuf.RoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Room_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Room_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoeaten.et.protobuf.CommandProtobuf.Room.class, com.taoeaten.et.protobuf.CommandProtobuf.Room.Builder.class);
      }

      // Construct using com.taoeaten.et.protobuf.CommandProtobuf.Room.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_Room_descriptor;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Room getDefaultInstanceForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.Room.getDefaultInstance();
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Room build() {
        com.taoeaten.et.protobuf.CommandProtobuf.Room result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.Room buildPartial() {
        com.taoeaten.et.protobuf.CommandProtobuf.Room result = new com.taoeaten.et.protobuf.CommandProtobuf.Room(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoeaten.et.protobuf.CommandProtobuf.Room) {
          return mergeFrom((com.taoeaten.et.protobuf.CommandProtobuf.Room)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoeaten.et.protobuf.CommandProtobuf.Room other) {
        if (other == com.taoeaten.et.protobuf.CommandProtobuf.Room.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoomId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoeaten.et.protobuf.CommandProtobuf.Room parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoeaten.et.protobuf.CommandProtobuf.Room) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 roomId = 1;
      private int roomId_ ;
      /**
       * <code>required int32 roomId = 1;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 roomId = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int32 roomId = 1;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roomId = 1;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taoeaten.et.protobuf.Room)
    }

    static {
      defaultInstance = new Room(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taoeaten.et.protobuf.Room)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoeaten_et_protobuf_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taoeaten_et_protobuf_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoeaten_et_protobuf_Room_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taoeaten_et_protobuf_Room_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\030com.taoeaten.et.protobu" +
      "f\"|\n\007Command\022\r\n\005cmdNo\030\001 \002(\005\022\020\n\010userName\030" +
      "\002 \002(\t\022\016\n\006roomNo\030\003 \001(\005\022\021\n\tuserReady\030\004 \001(\005" +
      "\022-\n\005rooms\030\005 \003(\0132\036.com.taoeaten.et.protob" +
      "uf.Room\"\026\n\004Room\022\016\n\006roomId\030\001 \002(\005B+\n\030com.t" +
      "aoeaten.et.protobufB\017CommandProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_taoeaten_et_protobuf_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_taoeaten_et_protobuf_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taoeaten_et_protobuf_Command_descriptor,
              new java.lang.String[] { "CmdNo", "UserName", "RoomNo", "UserReady", "Rooms", });
          internal_static_com_taoeaten_et_protobuf_Room_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_taoeaten_et_protobuf_Room_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taoeaten_et_protobuf_Room_descriptor,
              new java.lang.String[] { "RoomId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
