// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.taoeaten.et.protobuf;

public final class CommandProtobuf {
  private CommandProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface cmdInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmdNo = 1;
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    boolean hasCmdNo();
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    int getCmdNo();

    // required string cmdContent = 3;
    /**
     * <code>required string cmdContent = 3;</code>
     */
    boolean hasCmdContent();
    /**
     * <code>required string cmdContent = 3;</code>
     */
    java.lang.String getCmdContent();
    /**
     * <code>required string cmdContent = 3;</code>
     */
    com.google.protobuf.ByteString
        getCmdContentBytes();
  }
  /**
   * Protobuf type {@code com.taoeaten.et.protobuf.cmdInfo}
   */
  public static final class cmdInfo extends
      com.google.protobuf.GeneratedMessage
      implements cmdInfoOrBuilder {
    // Use cmdInfo.newBuilder() to construct.
    private cmdInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private cmdInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final cmdInfo defaultInstance;
    public static cmdInfo getDefaultInstance() {
      return defaultInstance;
    }

    public cmdInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private cmdInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmdNo_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              cmdContent_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_cmdInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.class, com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<cmdInfo> PARSER =
        new com.google.protobuf.AbstractParser<cmdInfo>() {
      public cmdInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new cmdInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<cmdInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmdNo = 1;
    public static final int CMDNO_FIELD_NUMBER = 1;
    private int cmdNo_;
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    public boolean hasCmdNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmdNo = 1;</code>
     */
    public int getCmdNo() {
      return cmdNo_;
    }

    // required string cmdContent = 3;
    public static final int CMDCONTENT_FIELD_NUMBER = 3;
    private java.lang.Object cmdContent_;
    /**
     * <code>required string cmdContent = 3;</code>
     */
    public boolean hasCmdContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string cmdContent = 3;</code>
     */
    public java.lang.String getCmdContent() {
      java.lang.Object ref = cmdContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmdContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cmdContent = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCmdContentBytes() {
      java.lang.Object ref = cmdContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      cmdNo_ = 0;
      cmdContent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmdNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getCmdContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCmdContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoeaten.et.protobuf.cmdInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taoeaten.et.protobuf.CommandProtobuf.cmdInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_cmdInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.class, com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.Builder.class);
      }

      // Construct using com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmdNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo getDefaultInstanceForType() {
        return com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.getDefaultInstance();
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo build() {
        com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo buildPartial() {
        com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo result = new com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdNo_ = cmdNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdContent_ = cmdContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo) {
          return mergeFrom((com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo other) {
        if (other == com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo.getDefaultInstance()) return this;
        if (other.hasCmdNo()) {
          setCmdNo(other.getCmdNo());
        }
        if (other.hasCmdContent()) {
          bitField0_ |= 0x00000002;
          cmdContent_ = other.cmdContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdNo()) {
          
          return false;
        }
        if (!hasCmdContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoeaten.et.protobuf.CommandProtobuf.cmdInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmdNo = 1;
      private int cmdNo_ ;
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public boolean hasCmdNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public int getCmdNo() {
        return cmdNo_;
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public Builder setCmdNo(int value) {
        bitField0_ |= 0x00000001;
        cmdNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmdNo = 1;</code>
       */
      public Builder clearCmdNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdNo_ = 0;
        onChanged();
        return this;
      }

      // required string cmdContent = 3;
      private java.lang.Object cmdContent_ = "";
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public boolean hasCmdContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public java.lang.String getCmdContent() {
        java.lang.Object ref = cmdContent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cmdContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCmdContentBytes() {
        java.lang.Object ref = cmdContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public Builder setCmdContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cmdContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public Builder clearCmdContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdContent_ = getDefaultInstance().getCmdContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string cmdContent = 3;</code>
       */
      public Builder setCmdContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cmdContent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taoeaten.et.protobuf.cmdInfo)
    }

    static {
      defaultInstance = new cmdInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taoeaten.et.protobuf.cmdInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taoeaten_et_protobuf_cmdInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\030com.taoeaten.et.protobuf\"," +
      "\n\007cmdInfo\022\r\n\005cmdNo\030\001 \002(\005\022\022\n\ncmdContent\030\003" +
      " \002(\tB+\n\030com.taoeaten.et.protobufB\017Comman" +
      "dProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_taoeaten_et_protobuf_cmdInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taoeaten_et_protobuf_cmdInfo_descriptor,
              new java.lang.String[] { "CmdNo", "CmdContent", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
