// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatCommand.proto

package com.taoeaten.et.protobuf;

public final class ChatCommandProtobuf {
  private ChatCommandProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FriendCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.taoeaten.et.protobuf.FriendCommand}
   *
   * <pre>
   **
   * </pre>
   */
  public static final class FriendCommand extends
      com.google.protobuf.GeneratedMessage
      implements FriendCommandOrBuilder {
    // Use FriendCommand.newBuilder() to construct.
    private FriendCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FriendCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FriendCommand defaultInstance;
    public static FriendCommand getDefaultInstance() {
      return defaultInstance;
    }

    public FriendCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FriendCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_FriendCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.class, com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<FriendCommand> PARSER =
        new com.google.protobuf.AbstractParser<FriendCommand>() {
      public FriendCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FriendCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FriendCommand> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoeaten.et.protobuf.FriendCommand}
     *
     * <pre>
     **
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_FriendCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.class, com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.Builder.class);
      }

      // Construct using com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor;
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand getDefaultInstanceForType() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.getDefaultInstance();
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand build() {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand buildPartial() {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand result = new com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand) {
          return mergeFrom((com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand other) {
        if (other == com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoeaten.et.protobuf.ChatCommandProtobuf.FriendCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taoeaten.et.protobuf.FriendCommand)
    }

    static {
      defaultInstance = new FriendCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taoeaten.et.protobuf.FriendCommand)
  }

  public interface ChatCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 fromUser = 1;
    /**
     * <code>required int32 fromUser = 1;</code>
     */
    boolean hasFromUser();
    /**
     * <code>required int32 fromUser = 1;</code>
     */
    int getFromUser();

    // required int32 toUser = 2;
    /**
     * <code>required int32 toUser = 2;</code>
     */
    boolean hasToUser();
    /**
     * <code>required int32 toUser = 2;</code>
     */
    int getToUser();

    // required string content = 3;
    /**
     * <code>required string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.taoeaten.et.protobuf.ChatCommand}
   */
  public static final class ChatCommand extends
      com.google.protobuf.GeneratedMessage
      implements ChatCommandOrBuilder {
    // Use ChatCommand.newBuilder() to construct.
    private ChatCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatCommand defaultInstance;
    public static ChatCommand getDefaultInstance() {
      return defaultInstance;
    }

    public ChatCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromUser_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toUser_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_ChatCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.class, com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatCommand> PARSER =
        new com.google.protobuf.AbstractParser<ChatCommand>() {
      public ChatCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 fromUser = 1;
    public static final int FROMUSER_FIELD_NUMBER = 1;
    private int fromUser_;
    /**
     * <code>required int32 fromUser = 1;</code>
     */
    public boolean hasFromUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 fromUser = 1;</code>
     */
    public int getFromUser() {
      return fromUser_;
    }

    // required int32 toUser = 2;
    public static final int TOUSER_FIELD_NUMBER = 2;
    private int toUser_;
    /**
     * <code>required int32 toUser = 2;</code>
     */
    public boolean hasToUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 toUser = 2;</code>
     */
    public int getToUser() {
      return toUser_;
    }

    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>required string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fromUser_ = 0;
      toUser_ = 0;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFromUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fromUser_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, toUser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromUser_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, toUser_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.taoeaten.et.protobuf.ChatCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_ChatCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.class, com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.Builder.class);
      }

      // Construct using com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUser_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUser_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor;
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand getDefaultInstanceForType() {
        return com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.getDefaultInstance();
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand build() {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand buildPartial() {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand result = new com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUser_ = fromUser_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUser_ = toUser_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand) {
          return mergeFrom((com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand other) {
        if (other == com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand.getDefaultInstance()) return this;
        if (other.hasFromUser()) {
          setFromUser(other.getFromUser());
        }
        if (other.hasToUser()) {
          setToUser(other.getToUser());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromUser()) {
          
          return false;
        }
        if (!hasToUser()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.taoeaten.et.protobuf.ChatCommandProtobuf.ChatCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 fromUser = 1;
      private int fromUser_ ;
      /**
       * <code>required int32 fromUser = 1;</code>
       */
      public boolean hasFromUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 fromUser = 1;</code>
       */
      public int getFromUser() {
        return fromUser_;
      }
      /**
       * <code>required int32 fromUser = 1;</code>
       */
      public Builder setFromUser(int value) {
        bitField0_ |= 0x00000001;
        fromUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fromUser = 1;</code>
       */
      public Builder clearFromUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUser_ = 0;
        onChanged();
        return this;
      }

      // required int32 toUser = 2;
      private int toUser_ ;
      /**
       * <code>required int32 toUser = 2;</code>
       */
      public boolean hasToUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 toUser = 2;</code>
       */
      public int getToUser() {
        return toUser_;
      }
      /**
       * <code>required int32 toUser = 2;</code>
       */
      public Builder setToUser(int value) {
        bitField0_ |= 0x00000002;
        toUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 toUser = 2;</code>
       */
      public Builder clearToUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUser_ = 0;
        onChanged();
        return this;
      }

      // required string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.taoeaten.et.protobuf.ChatCommand)
    }

    static {
      defaultInstance = new ChatCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.taoeaten.et.protobuf.ChatCommand)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taoeaten_et_protobuf_FriendCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_taoeaten_et_protobuf_ChatCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatCommand.proto\022\030com.taoeaten.et.pro" +
      "tobuf\"\017\n\rFriendCommand\"@\n\013ChatCommand\022\020\n" +
      "\010fromUser\030\001 \002(\005\022\016\n\006toUser\030\002 \002(\005\022\017\n\007conte" +
      "nt\030\003 \002(\tB/\n\030com.taoeaten.et.protobufB\023Ch" +
      "atCommandProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_taoeaten_et_protobuf_FriendCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taoeaten_et_protobuf_FriendCommand_descriptor,
              new java.lang.String[] { });
          internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_taoeaten_et_protobuf_ChatCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_taoeaten_et_protobuf_ChatCommand_descriptor,
              new java.lang.String[] { "FromUser", "ToUser", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
